version: '3.7'

services:
    mailhog:
        container_name: ${PROJECT_NAME}-mailhog
        image: mailhog/mailhog
        networks:
            - local
        ports:
            - "1025:1025"
            - "8025:8025"

    blackfire:
        container_name: ${PROJECT_NAME}-blackfire
        image: blackfire/blackfire:2
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
        networks:
            - local

networks:
    local:
        name: local