version: '3.7'

services:
    db:
        container_name: ${PROJECT_NAME}-db
        image: mariadb:10.8
        volumes:
            - ./docker/.data/db:/var/lib/mysql
            - ./docker/logs/mariadb:/var/log/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            DOMAIN_NAME: ${PROJECT_NAME}.MARIADB.local
        ports:
            - ${MARIADB_PORT}:3306
        networks:
            - local

    php:
        container_name: ${PROJECT_NAME}-php
        build:
            context: docker/php
            target: ${PROJECT_ENV}
        volumes:
            - ./:/var/www/symfony
            - ./docker/logs/symfony:/var/www/symfony/app/logs
        networks:
            - local

    nginx:
        container_name: ${PROJECT_NAME}
        build:
            context: docker/nginx
            args:
                MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
                PROJECT_NAME: ${PROJECT_NAME}
        volumes:
            - ./docker/logs/nginx:/var/log/nginx
            - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        depends_on:
            - php
            - db
        ports:
            - ${NGINX_PORT}:80
        networks:
            - local

networks:
    local:
        name: local